# Generated by Django 5.1 on 2024-08-09 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookstore", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Response",
        ),
    ]
